# Generated by Django 6.0.4 on 2026-04-14 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cultural', 'Cultural'), ('sports', 'Sports'), ('food', 'Food & Dining'), ('music', 'Music & Entertainment'), ('religious', 'Religious'), ('community', 'Community Meetup'), ('education', 'Education & Workshop'), ('other', 'Other')], default='community', max_length=20)),
                ('event_date', models.DateTimeField(help_text='Date and time the event starts')),
                ('event_end_date', models.DateTimeField(blank=True, help_text='Date and time the event ends', null=True)),
                ('venue', models.CharField(blank=True, help_text='Full venue address', max_length=300)),
                ('organiser', models.CharField(blank=True, help_text='Name of the organising person or group', max_length=200)),
                ('is_free', models.BooleanField(default=True, help_text='Is this event free to attend?')),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, help_text='Ticket price in AUD — leave empty if free', max_digits=8, null=True)),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees — leave empty for unlimited', null=True)),
                ('is_online', models.BooleanField(default=False, help_text='Is this a virtual/online event?')),
                ('event_url', models.URLField(blank=True, help_text='Link to event page, tickets or registration')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_detail', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['event_date'],
            },
        ),
    ]
