# Generated by Django 6.0.4 on 2026-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees', null=True),
        ),
    ]
