# Generated by Django 6.0.4 on 2026-04-14 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant & Cafe'), ('grocery', 'Grocery & Food Store'), ('travel', 'Travel & Tourism'), ('beauty', 'Beauty & Salon'), ('health', 'Health & Medical'), ('legal', 'Legal & Accounting'), ('education', 'Education & Tutoring'), ('religious', 'Religious Services'), ('construction', 'Construction & Trade'), ('transport', 'Transport & Logistics'), ('finance', 'Finance & Money Transfer'), ('freelancer', 'Freelancer & Pujari'), ('retail', 'Retail & Shopping'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(help_text='About the business')),
                ('is_nepalese_owned', models.BooleanField(default=True, help_text='Is this business owned by a Nepalese person?')),
                ('address', models.CharField(blank=True, max_length=300)),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory')], default='NSW', max_length=10)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('abn', models.CharField(blank=True, help_text='Australian Business Number — kept private', max_length=20)),
                ('established_year', models.PositiveIntegerField(blank=True, help_text='Year the business was established', null=True)),
                ('operating_hours', models.TextField(blank=True, help_text='e.g. Mon-Fri 9am-5pm, Sat 10am-3pm')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by NepSaathi admin')),
                ('is_active', models.BooleanField(default=True, help_text='Is the business currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user who registered this business', on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses',
                'ordering': ['-is_verified', '-created_at'],
            },
        ),
    ]
