# Generated by Django 6.0.4 on 2026-04-16 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['category'], name='businesses_categor_505809_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['state'], name='businesses_state_fba1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_verified'], name='businesses_is_veri_337b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active'], name='businesses_is_acti_8eca54_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner'], name='businesses_owner_i_1d3ff5_idx'),
        ),
    ]
