# Generated by Django 6.0.4 on 2026-04-30 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_businessreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or duplicate'), ('fake', 'Fake or misleading'), ('inappropriate', 'Inappropriate content'), ('scam', 'Scam or fraud'), ('wrong_category', 'Wrong category'), ('other', 'Other')], default='spam', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_reports',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'business')},
            },
        ),
    ]
