# Generated by Django 6.0.4 on 2026-05-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_businessimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text='When the featured status expires', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured via Stripe payment — shown at top of directory'),
        ),
    ]
