# Generated by Django 6.0.4 on 2026-08-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_featured_businesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='booking_link',
            field=models.URLField(blank=True, help_text='Link for bookings or appointments (Calendly, phone booking page, etc.)'),
        ),
    ]
