# Generated by Django 6.0.4 on 2026-04-13 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('private', 'Private Room'), ('shared', 'Shared Room'), ('entire', 'Entire Property'), ('studio', 'Studio')], default='private', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Weekly rent in AUD', max_digits=8)),
                ('furnishing', models.CharField(choices=[('furnished', 'Fully Furnished'), ('partial', 'Partially Furnished'), ('unfurnished', 'Unfurnished')], default='furnished', max_length=20)),
                ('bond', models.CharField(choices=[('2_weeks', '2 Weeks'), ('4_weeks', '4 Weeks'), ('6_weeks', '6 Weeks'), ('negotiable', 'Negotiable')], default='4_weeks', max_length=20)),
                ('bills_included', models.BooleanField(default=False, help_text='Are electricity, water, internet included in the rent?')),
                ('available_from', models.DateField(blank=True, help_text='Date the room is available from', null=True)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('max_occupants', models.PositiveIntegerField(default=1, help_text='Maximum number of people allowed')),
                ('nepalese_household', models.BooleanField(default=False, help_text='Is this a Nepalese household?')),
                ('pets_allowed', models.BooleanField(default=False)),
                ('parking_available', models.BooleanField(default=False)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_detail', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
            },
        ),
    ]
