# Generated by Django 6.0.4 on 2026-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bills_included',
            field=models.BooleanField(default=False, help_text='Are electricity, water, internet included?'),
        ),
    ]
