# Generated by Django 6.0.4 on 2026-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_bills_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='street_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
