# Generated by Django 6.0.4 on 2026-08-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittancerate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
