# Generated by Django 6.0.4 on 2026-08-11 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory')], max_length=3)),
                ('city', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('general', 'General Community'), ('students', 'Students'), ('jobs', 'Jobs & Work'), ('accommodation', 'Accommodation'), ('business', 'Business'), ('religion', 'Religion & Culture'), ('sports', 'Sports & Fitness'), ('women', 'Women'), ('other', 'Other')], default='general', max_length=20)),
                ('link', models.URLField()),
                ('member_count', models.CharField(blank=True, help_text='Display string, e.g. "500+"', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin has confirmed this group is legitimate')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'whatsapp_groups',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisaTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(choices=[('485', 'Temporary Graduate (485)'), ('189', 'Skilled Independent (189)'), ('190', 'Skilled Nominated (190)'), ('491', 'Skilled Work Regional (491)'), ('500', 'Student (500)'), ('482', 'Employer Sponsored (482)'), ('820', 'Partner (820/801)'), ('other', 'Other')], max_length=10)),
                ('lodged_month', models.CharField(max_length=7)),
                ('granted_month', models.CharField(blank=True, max_length=7)),
                ('state_lodged', models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory')], max_length=3)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('anzsco_code', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('is_granted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_timelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visa_timelines',
                'ordering': ['-created_at'],
            },
        ),
    ]
