# Generated by Django 6.0.4 on 2026-08-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzsco_code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('list_type', models.CharField(choices=[('MLTSSL', 'Medium and Long-term Strategic Skills List'), ('STSOL', 'Short-term Skilled Occupation List'), ('ROL', 'Regional Occupation List'), ('NONE', 'Not currently on a skilled list')], max_length=10)),
                ('eligible_visas', models.CharField(blank=True, help_text='Comma-separated, e.g. "189,190,491"', max_length=60)),
                ('alternative_titles', models.CharField(blank=True, help_text='Common job titles for this ANZSCO code', max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('last_updated', models.DateField(help_text='Last verified against DOHA skilled occupation list')),
            ],
            options={
                'db_table': 'visa_occupations',
                'ordering': ['anzsco_code'],
            },
        ),
        migrations.CreateModel(
            name='InvitationRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_date', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('visa_type', models.CharField(choices=[('189', 'Skilled Independent (189)'), ('190', 'Skilled Nominated (190)'), ('491', 'Skilled Work Regional (491)')], max_length=10)),
                ('lowest_score', models.PositiveSmallIntegerField()),
                ('invitations_issued', models.PositiveIntegerField()),
                ('tiebreaker_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visa_invitation_rounds',
                'ordering': ['-round_date', 'visa_type'],
                'unique_together': {('round_date', 'visa_type')},
            },
        ),
    ]
