# Generated by Django 6.0.4 on 2026-08-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_occupation_invitationround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationround',
            name='lowest_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Lowest points score across all occupations; null if not published', null=True),
        ),
    ]
