# Generated by Django 6.0.4 on 2026-05-11 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_featured_businesses'),
        ('listings', '0013_rename_listingview_table'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpayment',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_payments', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='featuredpayment',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_payments', to='listings.listing'),
        ),
    ]
