# Generated by Django 6.0.4 on 2026-04-13 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('casual', 'Casual'), ('contract', 'Contract'), ('internship', 'Internship'), ('volunteer', 'Volunteer')], default='casual', max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Salary amount in AUD', max_digits=10, null=True)),
                ('salary_type', models.CharField(choices=[('hourly', 'Per Hour'), ('weekly', 'Per Week'), ('monthly', 'Per Month'), ('yearly', 'Per Year'), ('negotiable', 'Negotiable')], default='hourly', max_length=20)),
                ('experience_required', models.CharField(blank=True, max_length=100)),
                ('qualifications', models.TextField(blank=True)),
                ('is_urgent', models.BooleanField(default=False, help_text='Mark as urgent to highlight the listing')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_detail', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
            },
        ),
    ]
