# Generated by Django 6.0.4 on 2026-08-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_pollvote_unique_voter_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('looking_for', 'Looking For'), ('announcement', 'Announcement'), ('buy_sell', 'Buy / Sell'), ('warning', 'Warning'), ('visa', 'Visa & Immigration'), ('accommodation', 'Accommodation'), ('jobs', 'Jobs & Work'), ('events', 'Events'), ('business', 'Business'), ('general', 'General')], db_index=True, default='discussion', max_length=20),
        ),
    ]
