# Generated by Django 6.0.4 on 2026-04-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('news', 'Community News'), ('sale', 'Item for Sale'), ('service', 'Service Offered'), ('general', 'General'), ('lost_found', 'Lost & Found'), ('education', 'Education')], default='general', help_text='Category of the announcement', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in AUD — only for sale items', max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('na', 'Not Applicable')], default='na', help_text='Condition of item — only for sale items', max_length=20)),
                ('is_free', models.BooleanField(default=False, help_text='Is this item or service free?')),
                ('is_urgent', models.BooleanField(default=False, help_text='Mark as urgent to highlight the announcement')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_detail', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
            },
        ),
    ]
