# Generated by Django 6.0.4 on 2026-04-16 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_savedlisting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or duplicate'), ('fake', 'Fake or misleading'), ('inappropriate', 'Inappropriate content'), ('scam', 'Scam or fraud'), ('wrong_category', 'Wrong category'), ('other', 'Other')], default='spam', max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional details about the report')),
                ('is_reviewed', models.BooleanField(default=False, help_text='Has admin reviewed this report?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing_reports',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
