# Generated by Django 6.0.4 on 2026-04-16 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='listings_status_c3eaec_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_type'], name='listings_listing_5f35f5_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['state'], name='listings_state_ab84b4_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['user'], name='listings_user_id_8788a1_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['expires_at'], name='listings_expires_96bc56_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='listings_created_4615f6_idx'),
        ),
    ]
