# Generated by Django 6.0.4 on 2026-04-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_listings_status_c3eaec_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_under_review',
            field=models.BooleanField(default=False),
        ),
    ]
