# Generated by Django 6.0.4 on 2026-04-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listingview'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_wanted',
            field=models.BooleanField(default=False),
        ),
    ]
