# Generated by Django 6.0.4 on 2026-05-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_type_notice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listingview',
            new_name='listing_vie_listing_5c2d05_idx',
            old_name='listings_li_listing_35db33_idx',
        ),
        migrations.RenameIndex(
            model_name='listingview',
            new_name='listing_vie_listing_9f8be9_idx',
            old_name='listings_li_listing_56ea98_idx',
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('job', 'Job'), ('room', 'Room'), ('event', 'Event'), ('business', 'Business'), ('notice', 'Notice')], help_text='Type of listing: job, room, event, business or notice', max_length=20),
        ),
        migrations.AlterModelTable(
            name='listingview',
            table='listing_views',
        ),
    ]
