# Generated by Django 6.0.4 on 2026-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_rename_listingview_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
