# Generated by Django 6.0.4 on 2026-06-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_backfill_reviewed_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='expiry_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
