# Generated by Django 6.0.4 on 2026-08-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_add_expiry_warning_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
