# Generated by Django 6.0.4 on 2026-08-17 22:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


def backfill_search_vectors(apps, schema_editor):
    """Populate search_vector for all existing listings using raw SQL
    so we get proper tsvector weights without re-triggering signals."""
    schema_editor.execute("""
        UPDATE listings
        SET search_vector =
            setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(location, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(description, '')), 'C')
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_add_lat_lng'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='listing_search_vector_gin'),
        ),
        migrations.RunPython(backfill_search_vectors, migrations.RunPython.noop),
    ]
