# Generated by Django 6.0.4 on 2026-08-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_add_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
