# Generated by Django 6.0.4 on 2026-09-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_add_tags_to_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_admin_removed',
            field=models.BooleanField(default=False, help_text='Set to True only when an admin explicitly removes the listing — used for violation tracking'),
        ),
    ]
