# Generated by Django 6.0.4 on 2026-09-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_add_is_admin_removed_to_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text='When the featured period ends; None means not currently featured via payment', null=True),
        ),
    ]
