# Generated by Django 6.0.4 on 2026-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_add_featured_until_to_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
