# Generated by Django 6.0.4 on 2026-09-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_add_featured_warning_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bumped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
