# Generated by Django 6.0.4 on 2026-08-08 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=2000)),
                ('category', models.CharField(choices=[('job', 'Looking for Work'), ('room', 'Looking for Room'), ('services', 'Looking for Services'), ('other', 'Other')], default='other', max_length=20)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reverse_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tutoring', 'Tutoring / Teaching'), ('translation', 'Translation / Interpretation'), ('it', 'IT & Tech'), ('photography', 'Photography / Video'), ('cooking', 'Cooking / Events'), ('accounting', 'Accounting / Tax'), ('transport', 'Transport / Delivery'), ('cleaning', 'Cleaning'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(max_length=2000)),
                ('rate', models.CharField(blank=True, max_length=100)),
                ('rate_type', models.CharField(choices=[('hourly', 'Per Hour'), ('fixed', 'Fixed Price'), ('negotiable', 'Negotiable')], default='negotiable', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
