# Generated by Django 6.0.4 on 2026-08-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reverserequest',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
