# Generated by Django 6.0.4 on 2026-04-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_avatar',
            field=models.URLField(blank=True, help_text='Google profile picture URL'),
        ),
    ]
