# Generated by Django 6.0.4 on 2026-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_google_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='', help_text='Custom uploaded profile picture URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_avatar',
            field=models.URLField(blank=True, help_text='Google profile picture URL — set automatically on Google login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified by NepSaathi admin'),
        ),
    ]
