# Generated by Django 6.0.4 on 2026-09-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('google', 'Google Search'), ('friend', 'Friend / Word of mouth'), ('community', 'Nepali community group'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
