# Generated by Django 6.0.4 on 2026-05-10 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(choices=[('not_enough_listings', 'Not enough listings in my area'), ('hard_to_navigate', 'Hard to navigate'), ('just_browsing', 'Just browsing'), ('missing_feature', 'Missing a feature'), ('technical_issue', 'Technical issue'), ('other', 'Other')], max_length=50)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
