# Generated by Django 6.0.4 on 2026-09-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
