# Generated by Django 6.0.4 on 2026-09-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_add_message_to_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackresponse',
            name='reason',
            field=models.CharField(blank=True, choices=[('not_enough_listings', 'Not enough listings in my area'), ('hard_to_navigate', 'Hard to navigate'), ('just_browsing', 'Just browsing'), ('missing_feature', 'Missing a feature'), ('technical_issue', 'Technical issue'), ('other', 'Other')], default='', max_length=50),
        ),
    ]
